tek_sayilar = set( [1,2,3,5,7,9])
cift_sayilar= set([2,4,6,8])
asal_sayilar= set([2,3,5,7])
#print(tek_sayilar.intersection(cift_sayilar))
#print(tek_sayilar.union(cift_sayilar))
print(tek_sayilar.intersection(asal_sayilar))